version: 2

sources:
  - name: uk_ev_raw
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: uk_ev_raw
    tables:
      - name: raw_bank_of_england_eur_gbp_fx
      - name: raw_european_wholesale_electricity_prices
      - name: raw_desnz_petroleum_products_prices
      - name: raw_dvla_veh1103
      - name: raw_dvla_veh1153
